// Mock mode: placeholder data generated by walking shared/contract.schema.json.
// Every string is "Placeholder <field>", every date is a fixed neutral date,
// every number a round placeholder. Nothing here comes from the case.
// The few fix-ups below only keep references consistent (ids that must point at
// each other) so every screen can be exercised; the river figures are made up.

let schemaPromise;
const loadSchema = () => (schemaPromise ??= fetch('/api/contract.schema.json').then((r) => r.json()));

const PLACEHOLDER_DATE = '2000-01-01';
const PLACEHOLDER_TIME = '2000-01-01T09:00:00Z';
const PIXEL = 'data:image/svg+xml;utf8,' + encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" width="612" height="792" viewBox="0 0 612 792">' +
  '<rect width="612" height="792" fill="#eef0f3"/><rect x="48" y="64" width="516" height="24" fill="#cfd4db"/>' +
  Array.from({ length: 16 }, (_, i) => `<rect x="48" y="${120 + i * 30}" width="${i % 3 === 2 ? 340 : 516}" height="10" fill="#d9dde3"/>`).join('') +
  '<text x="306" y="740" font-family="sans-serif" font-size="20" text-anchor="middle" fill="#8a93a0">placeholder page image</text></svg>');

function makeGen(schema) {
  const defs = schema.$defs;
  const st = { n: 0, i: 0, money: 0 };

  function str(name) {
    if (/href$/.test(name)) return `/mock/${name}`;
    if (/(^|_)(at|date|due|since|end|as_of|asked|requested|received)(_|$)/.test(name) || /_(at|date)$/.test(name) || name === 'as_of') {
      return /(_at|^at|as_of|since|generated)/.test(name) ? PLACEHOLDER_TIME : PLACEHOLDER_DATE;
    }
    return `Placeholder ${name.replace(/_/g, ' ')}`;
  }

  function gen(node, name, depth = 0) {
    if (depth > 12) return null;
    if (node.$ref) return gen(defs[node.$ref.split('/').pop()], name, depth + 1);
    if (node.anyOf) return gen(node.anyOf.find((n) => n.type !== 'null') || node.anyOf[0], name, depth + 1);
    if (node.enum) return node.enum[st.n++ % node.enum.length];
    switch (node.type) {
      case 'string': return str(name);
      case 'boolean': return false;
      case 'integer': {
        st.i += 1;
        if (node.maximum != null) return (st.i % node.maximum) + (node.minimum ?? 0) || node.minimum || 1;
        return st.i;
      }
      case 'number': st.money += 1; return /percent/.test(name) ? 33 : 1000 * ((st.money % 5) + 1);
      case 'array': return [0, 1].map(() => gen(node.items || {}, name, depth + 1));
      case 'object': {
        if (node.properties) {
          const out = {};
          for (const [k, v] of Object.entries(node.properties)) out[k] = gen(v, k, depth + 1);
          if ('href' in out && 'kind' in out && 'clio_id' in out) out.href = `/api/matters/0/sources/${out.kind}/${out.clio_id}`;
          return out;
        }
        if (node.additionalProperties) {
          return Object.fromEntries(['a', 'b'].map((k) => [`placeholder_${k}`, gen(node.additionalProperties, name, depth + 1)]));
        }
        return {};
      }
      default: return null;
    }
  }
  return { gen, defs };
}

let store;
async function getStore() {
  if (store) return store;
  const schema = await loadSchema();
  const { gen } = makeGen(schema);
  const top = (key) => gen(schema.properties[key], key);

  const matters = top('matters');
  matters.connected = true;
  matters.live = true;
  while (matters.items.length < 2) matters.items.push({ ...matters.items[0] });   // two placeholder cases, so switching can be exercised
  matters.items.forEach((m, i) => { m.id = i + 1; m.archived = false; m.client_name = `Placeholder client ${i + 1}`; m.display_number = `Placeholder number ${i + 1}`; });
  matters.selected_matter_id = matters.items[0].id;

  const c = top('case');
  c.meta.matter_id = matters.items[0].id;
  c.meta.digest.state = 'complete';
  c.meta.digest.items_total = 8;
  c.meta.digest.items_digested = 8;
  c.matter.id = matters.items[0].id;

  // contacts: one client, two treating providers
  const roles = ['client', 'provider', 'provider', 'insurer'];
  c.contacts.forEach((x, i) => { x.id = 100 + i; x.role = roles[i % roles.length]; });
  while (c.contacts.length < 3) c.contacts.push({ ...c.contacts[0], id: 100 + c.contacts.length, role: 'provider' });
  c.contacts[0].role = 'client';
  c.contacts[1].role = 'provider';
  c.contacts[2].role = 'provider';
  c.matter.client = c.contacts[0];
  c.brief.client_photo = c.brief.client_photo && { ...c.brief.client_photo, image_href: PIXEL };

  // claims: first notes, second document
  c.claims.forEach((x, i) => { x.id = `claim-${i}`; x.origin = i % 2 ? 'document' : 'notes'; });
  c.conflicts.forEach((x, i) => {
    x.id = `conflict-${i}`;
    x.notes_claim_ids = ['claim-0'];
    x.document_claim_ids = ['claim-1'];
    x.severity = 3 - i;
    x.review = i ? 'confirmed' : 'unreviewed';
    x.review_href = `/api/matters/${c.meta.matter_id}/conflicts/${x.id}/review`;
  });

  // river: made-up descending figures so the picture is exercisable
  const kinds = ['value', 'coverage', 'gate', 'lien', 'net'];
  const inflows = [8000, 8000, 6000, 4500, 4000];
  const diverted = [0, 2000, 1500, 500, 0];
  c.river ??= { stages: [] };  // a stale schema has no River
  c.river.stages = kinds.map((kind, i) => {
    const base = c.river.stages[i % (c.river.stages.length || 1)] || { sources: [], derivation: 'computed' };
    return { ...base, id: `stage-${i}`, kind, label: `Placeholder ${kind}`, inflow: inflows[i], diverted: diverted[i],
      outflow: inflows[i] - diverted[i], status: ['assumed', 'confirmed', 'contested', 'confirmed', 'assumed'][i] };
  });
  c.river.unknown = [];
  // river v2 (guessed shape): components under the first stage, sum checks, a reading line
  const baseNode = c.nodes[0] || { derivation: 'computed', depends_on: [], claim_ids: [], sources: [], category: 'valuation' };
  c.nodes = [{ ...baseNode, id: 'node-value', kind: 'value', label: 'Placeholder value', parent_id: null },
    ...[['Placeholder component A', 3000, 'confirmed'], ['Placeholder component B', 3500, 'assumed'], ['Remainder: firm estimate, nothing itemised', 1500, 'assumed']].map(([label, amount, status], i) => ({
      ...baseNode, id: `node-c${i}`, kind: 'economic', label, amount, status, parent_id: 'node-value', basis: 'Placeholder basis in one line.', payer: i === 0 ? 'Placeholder payer' : null }))];
  c.river.checks = [{ id: 'sum:value', label: 'Components add up to the stated case value', ok: true, node_ids: ['node-value'] }];
  c.river.reading = 'Placeholder reading line, built by the server: how much is documented, how much is estimate, how much is held back.';
  c.river.net = 3500;

  // moves (guessed shape; replaced by the real Move when the contract lands)
  c.moves = [1, 2, 3, 4, 5].map((n) => ({
    id: `move-${n}`, title: `Placeholder move ${n}`, why: 'Placeholder reason in one line.', owed_by: 'Placeholder name', owed_by_role: ['provider', 'client', 'firm'][n % 3],
    waiting_days: 10 * n, times_asked: n, amount: 1000 * n, source: c.claims[0].source,
    draft_text: n % 2 ? 'Placeholder draft message for the recipient.' : null, audience: 'provider', audience_contact_id: c.contacts[1].id,
  }));

  c.incoming = [{ id: 'communication:1', contact_id: c.contacts[1].id, contact_name: 'Placeholder name', contact_role: 'provider', date: PLACEHOLDER_DATE, subject: 'Placeholder subject', counts: { contradicted: 1, supported: 1 },
    source: c.claims[0].source, spans: [{ text: 'Placeholder statement from outside.', verdict: 'contradicted', message: 'Placeholder: the file says otherwise.', claim_ids: ['claim-0'], sources: [c.claims[0].source] }] }];
  c.meta.digest.reconcile_stale = true; c.meta.digest.changed_since_reconcile = 2; c.meta.digest.reconciled_at = PLACEHOLDER_TIME; c.meta.digest.reconcile_estimate_seconds = 40; c.meta.digest.reconcile_estimate_usd = 0.35; c.meta.digest.reconcile_href = '/api/matters/0/digest?reconcile=true';
  if (c.conflicts[0]) c.conflicts[0].stale = true;

  // timeline: 12 events, a third of them "matters"
  c.timeline.length = 0;
  for (let i = 0; i < 12; i += 1) {
    c.timeline.push({
      ...gen(schema.$defs.TimelineEvent, 'timeline'),
      id: `ev-${i}`, date: `2000-01-${String(i + 1).padStart(2, '0')}`, importance: (i % 3) + 1,
      date_source: i % 2 ? 'document' : 'clio', label: `Placeholder event ${i + 1}`,
    });
  }

  // agenda buckets
  for (const b of ['overdue', 'coming', 'waiting']) {
    c.agenda[b].forEach((x, i) => { x.bucket = b; x.id = `${b}-${i}`; x.days_from_today = b === 'overdue' ? -3 - i : 4 + i; });
  }
  c.changes.items.forEach((x, i) => { x.change = ['new', 'updated', 'removed'][i % 3]; });

  // providers share the provider contacts
  c.providers = [1, 2].map((ci, i) => {
    const p = { ...gen(schema.$defs.ProviderPanel, 'provider') };
    p.contact = c.contacts[ci];
    p.policy = { contact_id: c.contacts[ci].id, allowed_categories: ['status', 'bills', 'records', 'asks', 'coverage'], hidden_item_ids: [], message: null, updated_at: null };
    p.preview_href = `/api/matters/${c.meta.matter_id}/providers/${c.contacts[ci].id}/preview`;
    p.shares = i === 0 ? p.shares.slice(0, 1) : [];
    p.policy.approved_asks = {};
    p.requests = i === 0 ? [{ id: 'rq1', kind: 'coverage', question: 'Is there coverage behind the case?', text: 'Placeholder detail from the provider.', created_at: PLACEHOLDER_TIME, state: 'open', answer: null, suggested: { action: 'enable_category', category: 'coverage', label: 'Turn on the coverage band for this provider' } }] : [];
    p.thread = [];
    p.thread = i === 0 ? [
      { id: 'm1', direction: 'from_firm', text: 'Placeholder outgoing message text.', at: PLACEHOLDER_TIME, overrides: [{ reason: 'Placeholder reason', text: 'Placeholder held sentence.', at: PLACEHOLDER_TIME }] },
      { id: 'm2', direction: 'from_provider', text: 'Placeholder incoming message text from the provider.', at: PLACEHOLDER_TIME }] : [];
    p.asks.forEach((a, j) => { a.id = `ask-${i}-${j}`; a.contact_id = c.contacts[ci].id; a.reply = null; a.replied_at = null; });
    return p;
  });

  if (new URLSearchParams(location.search).get('mock') === 'empty') {
    // a matter before the digest has run: lists empty, amounts unknown
    c.brief = { summary: [] };
    const st = (id, kind, label, inflow, diverted, outflow, status) => ({ id, node_id: id, kind, label, inflow, diverted, outflow, status, sources: [] });
    c.river = { fee_percent: null, net: null, unknown: ['gate', 'fee', 'net'], stages: [
      st('value', 'value', 'Case value', 8000, 0, 8000, 'assumed'),
      st('gate', 'gate', 'Coverage not yet confirmed', null, null, null, 'unknown'),
      st('cost', 'cost', 'Firm costs', 8000, 500, 7500, 'confirmed'),
      st('fee', 'fee', 'Fee not set', null, null, null, 'unknown'),
      st('net', 'net', 'Net', null, null, null, 'unknown')] };
    c.incoming = []; c.moves = []; c.conflicts = []; c.timeline = []; c.nodes = []; c.claims = [];
    c.agenda = { as_of: PLACEHOLDER_TIME, overdue: [], coming: [], waiting: [], done: [] };
    c.changes = { items: [], counts: {}, since: null };
    c.meta.digest = { state: 'not_started' };
    c.providers.forEach((p) => { p.asks = []; p.shares = []; p.records = {}; p.bills = {}; p.attendance = {}; });
  }
  const view = top('provider_view');
  const source = top('source_detail');
  source.page_image_href = PIXEL;
  store = { schema, matters, c, view, source, gen };
  // Console hooks to exercise live refresh in mock mode: __mock.reply(), __mock.open(), __mock.digest(n)
  window.__mock = {
    reply() { const a = c.providers[0].asks.find((x) => !x.reply); if (a) { a.reply = 'Placeholder reply'; a.replied_at = new Date().toISOString(); } },
    open() { const sh = c.providers[0].shares[0]; if (sh) { sh.first_opened_at ||= new Date().toISOString(); sh.open_count += 1; } },
    digest(done) { Object.assign(c.meta.digest, { state: done < 100 ? 'running' : 'complete', pages_total: 100, pages_digested: Math.min(done, 100) }); },
  };
  return store;
}

const LOCKED = new Set(['valuation', 'strategy', 'other_party', 'internal']);

function lens(s, contactId) {
  const p = s.c.providers.find((x) => x.contact.id === contactId) || s.c.providers[0];
  const allow = new Set(p.policy.allowed_categories);
  const v = structuredClone(s.view);
  v.provider = p.contact;
  v.client_name = s.c.matter.client?.name || 'Placeholder client';
  v.shared_categories = [...allow];
  v.message = p.policy.message;
  v.stage = allow.has('status') ? s.c.brief.stage : null;
  v.alive = allow.has('status') ? s.c.brief.alive : null;
  const hide = new Set(p.policy.hidden_item_ids || []);
  v.updates = allow.has('status') ? s.c.timeline.slice(0, 3).filter((e) => !hide.has(e.id)) : [];
  v.records = allow.has('records') ? p.records : null;
  v.bills = allow.has('bills') ? p.bills : null;
  v.attendance = allow.has('attendance') ? p.attendance : null;
  v.asks = allow.has('asks') ? p.asks.filter((a) => !hide.has(a.id)).map((a) => ({ ...a })) : [];
  v.request_kinds = { coverage: 'Is there coverage behind the case?', status: 'Where does the case stand?', records_needed: 'What records does the firm need from us?', payment_timing: 'When can we expect payment?', other: 'Something else' };
  v.requests = (p.requests || []).map((r) => ({ id: r.id, kind: r.kind, question: r.question, text: r.text, created_at: r.created_at, state: r.state, answer: r.answer, answered_at: r.answered_at }));
  v.thread = (p.thread || []).map((x) => ({ ...x }));
  v.coverage = allow.has('coverage')
    ? { ...v.coverage, shared: true, band: 'being_confirmed', display: 'Coverage being confirmed', sources: [] }
    : { ...v.coverage, shared: false, band: null, display: 'Not shared by the firm', sources: [] };
  v.withheld_counts = { valuation: 3, strategy: 5, internal: 12, other_party: 2 };
  v.warnings = [];
  v.content_hash = `hash-${(p.policy.message || '').length}-${p.policy.allowed_categories.length}`;
  return v;
}

let mockSignedIn = false;
// A second case for the mock: the same shape with every figure doubled and a different name.
function variant(c, n) {
  const v = structuredClone(c);
  const walk = (o) => {
    for (const k of Object.keys(o || {})) {
      const x = o[k];
      if (typeof x === 'number' && /amount|value|total|spend|limit/.test(k)) o[k] = x * (n + 1);
      else if (typeof x === 'string' && /^\$[\d,]+$/.test(x)) o[k] = `$${(Number(x.replace(/\D/g, '')) * (n + 1)).toLocaleString('en-US')}`;
      else if (x && typeof x === 'object') walk(x);
    }
  };
  walk(v.river); walk(v.brief);
  v.matter.id = n + 1; v.meta.matter_id = n + 1;
  if (v.matter.client) v.matter.client = { ...v.matter.client, name: `Placeholder client ${n + 1}` };
  v.matter.display_number = `Placeholder number ${n + 1}`;
  return v;
}
const caseIndex = (path) => { const m = path.match(/\/api\/matters\/(\d+)\//); return m ? (Number(m[1]) + 1) % 2 : 0; };   // odd ids are the first case, even ids the second

export async function mockRoute(rawPath, method, body) {
  (window.__mockLog ||= []).push(`${method || 'GET'} ${rawPath}`);
  if (new URLSearchParams(location.search).get('auth') === '1' && !mockSignedIn && rawPath.startsWith('/api/') && !rawPath.startsWith('/api/firm/')) {
    throw Object.assign(new Error('Firm sign-in required.'), { status: 401 });
  }
  if (rawPath === '/api/firm/login') {
    if (body.passcode !== 'placeholder') throw Object.assign(new Error('Wrong passcode.'), { status: 401 });
    mockSignedIn = true; return { signed_in: true };
  }
  const s = await getStore();
  const path = rawPath.split('?')[0];
  const ok = (v) => structuredClone(v);
  let m;
  if (path === '/api/matters') return ok(s.matters);
  if (path === '/api/settings/fee') {
    if (method === 'PUT') { s.fee = { percent: body.percent, basis: body.basis }; s.c.river.fee_percent = body.percent; }
    return s.fee || { percent: s.c.river.fee_percent ?? null, basis: 'gross' };
  }
  if (/\/check$/.test(path)) {
    // placeholder verdicts chosen by a hash of each sentence so every kind can be exercised
    const order = ['supported', 'contradicted', 'out_of_date', 'not_in_file'];
    const src = s.c.claims[0].source;
    const spans = [];
    const re = /[^.!?\n]+[.!?]*/g; let mt;
    while ((mt = re.exec(body.text)) !== null) {
      const t = mt[0].replace(/\s+$/, ''); const lead = t.length - t.trimStart().length;
      if (t.trim().length < 2) continue;
      let h = 0; for (const ch of t) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
      let verdict = order[h % 4];
      if (body.audience === 'provider' && /\b(settle|settlement|worth|valuation|demand)\b/i.test(t)) verdict = 'dont_send';
      const start = mt.index + lead, end = mt.index + t.length;
      const pending = body.max_tier === 1 && h % 2 === 0;
      const ev = (role) => ({ claim_id: 'claim-0', role, text: 'Placeholder claim text.', date: PLACEHOLDER_DATE, origin: 'notes', category: 'internal', source: src });
      spans.push({ id: `sp-${h}`, start, end, text: t.trimStart(), verdict: pending ? null : verdict, pending, partial: false,
        fact_verdict: verdict === 'dont_send' ? 'supported' : null, category: verdict === 'dont_send' ? 'valuation' : null,
        claim_ids: ['claim-0'], evidence: pending || verdict === 'not_in_file' ? [] : verdict === 'dont_send' ? [ev('discloses')] : verdict === 'out_of_date' ? [ev('superseded'), ev('supersedes')] : [ev(verdict === 'contradicted' ? 'contradicts' : 'supports')],
        replacement: !pending && (verdict === 'contradicted' || verdict === 'out_of_date') ? { start, end, text: 'Placeholder replacement', claim_id: 'claim-0' } : null,
        message: pending ? '' : `Placeholder reading for a ${verdict.replace('_', ' ')} sentence.`, tier: pending ? 1 : 2, cached: false, latency_ms: 20 + (h % 300) });
    }
    await new Promise((r) => setTimeout(r, body.max_tier === 1 ? 40 : 500));
    s.chk = (s.chk || 0) + spans.length;
    return { matter_id: 0, mode: body.mode, audience: body.audience, audience_contact_id: body.audience_contact_id, ledger_version: 'v', ledger_claims: 12,
      spans, pending: spans.filter((x) => x.pending).length, blocked: spans.some((x) => x.verdict === 'dont_send'), tier2_available: true, latency_ms: 40,
      stats: { sentences_checked: s.chk, cache_hits: 0, tier1_resolved: 0, tier2_calls: 0, tier1_p50_ms: 12, tier1_p95_ms: 30, tier2_p50_ms: 900, tier2_p95_ms: 1500, cost_usd: 0.0004 * s.chk, model: 'placeholder-model' } };
  }
  if (/\/providers\/\d+\/overrides$/.test(path)) return [{ share_id: null, item: 'message:m1', text: 'Placeholder held sentence.', category: 'valuation', state: 'dont_send', reason: 'Placeholder reason', at: PLACEHOLDER_TIME }];
  if (/\/incoming-checks\/unreviewed$/.test(path)) return { [s.c.providers[0].contact.id]: s.reviewState === 'unreviewed' || !s.reviewState ? 1 : 0 };
  if (/\/incoming-checks\/review$/.test(path)) { s.reviewState = body.review; return { checks: {}, reviews: { [body.item]: body.review }, unreviewed_contradictions: body.review === 'unreviewed' ? 1 : 0 }; }
  if (/\/providers\/\d+\/incoming-checks$/.test(path)) {
    const ev = [{ claim_id: 'c', role: 'contradicts', text: 'Placeholder claim', date: PLACEHOLDER_DATE, source: s.c.claims[0].source }];
    return { checks: { 'message:m2': { spans: [{ id: 's1', start: 0, end: 5, text: 'Placeholder statement from the provider.', verdict: 'contradicted', message: 'Placeholder: their figure differs from the file.', evidence: ev }, { id: 's2', start: 6, end: 9, text: 'Placeholder unassessed sentence.', verdict: null, evidence: [] }] },
      'request:rq1': { spans: [] } }, reviews: { 'message:m2': s.reviewState || 'unreviewed' }, unreviewed_contradictions: 1 };
  }
  if ((m = path.match(/\/providers\/(\d+)\/messages$/))) {
    const p = s.c.providers.find((x) => x.contact.id === Number(m[1]));
    if (/settle/i.test(body.text) && !body.override_reason) throw Object.assign(new Error('1 sentence in this text discloses something this provider is never shown. Edit the text, or give a reason to send it anyway.'), { status: 423 });
    const msg = { id: `m-${Date.now()}`, direction: 'from_firm', text: body.text, at: new Date().toISOString() };
    p.thread.push(msg); return { requests: ok(p.requests), thread: ok(p.thread) };
  }
  if ((m = path.match(/\/providers\/(\d+)\/requests\/([^/]+)\/answer$/))) {
    const p = s.c.providers.find((x) => x.contact.id === Number(m[1]));
    const r = p.requests.find((x) => x.id === decodeURIComponent(m[2]));
    if (body.action === 'reply' && /settle/i.test(body.text || '') && !body.override_reason) throw Object.assign(new Error('1 sentence in this text discloses something this provider is never shown.'), { status: 423 });
    r.state = body.action === 'decline' ? 'declined' : 'answered';
    r.answer = body.text || (body.action === 'decline' ? 'Placeholder canned decline.' : 'Placeholder: the firm updated what you can see.');
    r.answered_at = new Date().toISOString();
    p.thread.push({ id: `t-${Date.now()}`, direction: 'from_firm', text: r.answer, at: r.answered_at, request_id: r.id });
    return { requests: ok(p.requests), thread: ok(p.thread) };
  }
  if (/\/api\/share\/[^/]+\/requests$/.test(path)) {
    const p = s.c.providers[0];
    p.requests.push({ id: `rq-${Date.now()}`, kind: body.kind, question: s.view.request_kinds?.[body.kind] || body.kind, text: body.text, created_at: new Date().toISOString(), state: 'open', answer: null, suggested: { action: 'reply', label: 'Write a reply' } });
    return lens(s, p.contact.id);
  }
  if (/\/api\/share\/[^/]+\/messages$/.test(path)) {
    const p = s.c.providers[0];
    p.thread.push({ id: `m-${Date.now()}`, direction: 'from_provider', text: body.text, at: new Date().toISOString() });
    return lens(s, p.contact.id);
  }
  if (/\/graph$/.test(path)) { const g = await import('../v2/js/graph/standin.js'); return caseIndex(path) ? g.standinGraph({ nodes: 120, claims: 1500, seed: 11 }) : g.standinGraph(); }
  if (/\/cards\/design$/.test(path)) return { spec: { kind: 'list', title: 'Newest documents', source: 'documents', fields: ['name', 'received_at'], limit: 5, sort: { field: 'received_at', dir: 'desc' } } };
  if (/\/digest$/.test(path)) return ok(s.c.meta.digest);
  if (/\/sync$/.test(path)) return { matter_id: 1, requests: 0, changed: 0, kinds: {}, documents_downloaded: 0, warnings: [] };
  if (/\/opened$/.test(path)) return { previous: null, now: PLACEHOLDER_TIME };
  if (/\/case$/.test(path)) return caseIndex(path) ? variant(s.c, 1) : ok(s.c);
  if (path.includes('/sources/')) {
    const d = ok(s.source);
    const q = new URLSearchParams(rawPath.split('?')[1] || '');
    d.ref = { ...d.ref, href: rawPath, page: Number(q.get('page')) || 1 };
    d.page_count = 5;
    return d;
  }
  if ((m = path.match(/\/review$/))) return { review: body.review, reviewed_at: PLACEHOLDER_TIME };
  if ((m = path.match(/\/providers\/(\d+)\/policy$/))) {
    const p = s.c.providers.find((x) => x.contact.id === Number(m[1]));
    if (method === 'PUT') {
      const bad = (body.allowed_categories || []).find((x) => LOCKED.has(x));
      if (bad) throw Object.assign(new Error(`${bad} can never be shared`), { status: 422 });
      p.policy = { ...body, updated_at: PLACEHOLDER_TIME };
    }
    return ok(p.policy);
  }
  if ((m = path.match(/\/providers\/(\d+)\/preview$/))) return lens(s, Number(m[1]));
  if ((m = path.match(/\/providers\/(\d+)\/share$/))) {
    const p = s.c.providers.find((x) => x.contact.id === Number(m[1]));
    if (/settle/i.test(p.policy.message || '') && !body?.override_reason) throw Object.assign(new Error('1 sentence in this text discloses something this provider is never shown. Edit the text, or give a reason to send it anyway.'), { status: 423 });
    const entry = { ...ok(p.shares[0] || s.c.providers[0].shares[0] || {}), id: `share-${Date.now()}`, contact_id: p.contact.id,
      link_href: '/provider.html?token=placeholder', sent_at: new Date().toISOString(), first_opened_at: null, last_opened_at: null,
      open_count: 0, state: 'active', revoked_at: null, categories: p.policy.allowed_categories, item_count: 6 };
    entry.snapshot_href = `/api/matters/1/shares/${entry.id}/snapshot`;
    entry.revoke_href = `/api/matters/1/shares/${entry.id}/revoke`;
    p.shares.unshift(entry);
    return ok(entry);
  }
  if (/\/shares\/.+\/snapshot$/.test(path)) return lens(s, s.c.providers[0].contact.id);
  if ((m = path.match(/\/shares\/(.+)\/revoke$/))) {
    for (const p of s.c.providers) for (const sh of p.shares) if (sh.id === decodeURIComponent(m[1])) { sh.state = 'revoked'; sh.revoked_at = PLACEHOLDER_TIME; return ok(sh); }
    return {};
  }
  if ((m = path.match(/\/api\/share\/[^/]+\/asks\/([^/]+)\/reply$/))) {
    const v = lens(s, s.c.providers[0].contact.id);
    const ask = v.asks.find((a) => a.id === decodeURIComponent(m[1]));
    if (ask) { ask.reply = body.text; ask.replied_at = new Date().toISOString(); }
    return v;
  }
  if (/\/api\/share\/[^/]+$/.test(path)) return lens(s, s.c.providers[0].contact.id);
  return {};
}
